python/the-knights-who-say-ni

ni/__main__.py, ni/bpo.py, ni/github.py, ni/test/test_bpo.py, ni/test/test_github.py, ni/test/util.py
=> Check CLAs on bugs.python.org

ni/abc.py, ni/heroku.py, ni/test/test_heroku.py, ni/test/test_main.py
=> Add support for getting an auth token stored on the server host

ni/__main__.py, ni/abc.py, ni/github.py, ni/test/test_github.py, ni/test/test_main.py, ni/test/util.py
=> Use the contribution auth token in requests.

LICENSE
=> Add LICENSE details

.travis.yml
=> Cache dependencies for Travis

ni/__main__.py, ni/abc.py, ni/bpo.py, ni/heroku.py, ni/test/test_bpo.py, ni/test/test_heroku.py, ni/test/test_main.py, ni/test/util.py
=> Log CLA check details

ni/bpo.py, ni/test/test_bpo.py, ni/test/util.py
=> Filter and check result from bugs.python.org

ni/github.py, ni/test/examples/github/commits.json
=> Don't check for any GitHub-generated commits/authorships for CLA signing

.travis.yml
=> Use the latest release of coverage.py

README.md
=> Document how to deploy

ni/github.py, ni/test/examples/github/commits.json
=> Force emails to lowercase for consistent comparisons

ni/github.py, ni/test/examples/github/commits.json
=> Handle the case where an author isn't specified

.travis.yml, ni/abc.py, ni/github.py, ni/heroku.py, ni/test/test_github.py, ni/test/test_heroku.py, ni/test/util.py
=> Specify a user agent (when provided)

ni/github.py
=> Improve the message the bot leaves

.travis.yml
Closes #92 
Installs typed-ast before mypy.
=> Update mypy install for travis

ni/github.py
=> Add a 1 second delay for new PRs

README.md, app.json
- Create app.json.
- Add 'Deploy to Heroku' to README.md.
Closes https://github.com/python/the-knights-who-say-ni/issues/102
=> Add "Deploy to Heroku" button.

ni/github.py
=> Explain how to cause a new check

ni/__main__.py
Fixes https://github.com/python/the-knights-who-say-ni/issues/154
=> Don't use the loop argument

ni/github.py
=> Add the link on how to check if CLA has been received.

ni/github.py
Closes https://github.com/python/the-knights-who-say-ni/issues/159
=> Link to the check_python_cla website.

.gitignore, mypy.sh
Otherwise aiohttp would need to be typed by hand.
=> Loosen mypy requirements

README.md, ni/__main__.py, requirements.txt
=> Add sentry

runtime.txt
=> Use the latest Python runtime from Heroku

runtime.txt
=> Run under Python 3.7.6

runtime.txt
=> Use Python 3.7.7 runtime

runtime.txt
Closes https://github.com/python/the-knights-who-say-ni/issues/242
=> Use Python 3.7.9  runtime
